=== l3chtan/SSD/UE3/ssd-ss15-exercise3/resources/jeopardy.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xhtml="http://www.w3.org/1999/xhtml">
  
	<xsd:element name="jeopardy" type="jeopardy">
		<xsd:key name="userKeys">
			<xsd:selector xpath="users/user"/>
			<xsd:field xpath="@username"/>
		</xsd:key>
		
		<xsd:keyref name="playerRefs" refer="userKeys">
			<xsd:selector xpath="games/game/player"/>
			<xsd:field xpath="@ref"/>
		</xsd:keyref>
		
		<xsd:keyref name="playerRefs2" refer="userKeys">
			<xsd:selector xpath="games/game/asked/givenanswer"/>
			<xsd:field xpath="@player"/>
		</xsd:keyref>
		
		<xsd:key name="questionKeys">
			<xsd:selector xpath="categories/category/question"/>
			<xsd:field xpath="@id"/>
		</xsd:key>

    <xsd:keyref name="questionRefs" refer="questionKeys">
      <xsd:selector xpath="games/game/asked"/>
      <xsd:field xpath="@question"/>
    </xsd:keyref>
	</xsd:element>
	
	<xsd:complexType name="jeopardy">
		<xsd:sequence>
			<xsd:element name="overview" type="overview" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="categories" type="categories" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="users" type="users" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="games" type="games" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="categories">
		<xsd:sequence>
			<xsd:element name="category" type="category" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="category">
		<xsd:sequence>
		    <xsd:element name="question" type="question" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
    <xsd:attribute name="name" type="xsd:ID" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="question">
		<xsd:sequence>
			<xsd:element name="text" type="xsd:string"/>
			<xsd:element name="answer" type="answer" minOccurs="2" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
		<xsd:attribute name="value" type="values" use="required"/>
	</xsd:complexType>

  <xsd:simpleType name="values">
    <xsd:restriction base="xsd:decimal">
      <xsd:enumeration value="100"/>
      <xsd:enumeration value="200"/>
      <xsd:enumeration value="500"/>
      <xsd:enumeration value="750"/>
      <xsd:enumeration value="1000"/>
    </xsd:restriction>
  </xsd:simpleType>
	
	<xsd:complexType name="answer">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="correct" type="correct" default="no"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="users">
		<xsd:sequence>
			<xsd:element name="user" type="user" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="user">
		<xsd:sequence>
			<xsd:element name="password" type="xsd:string"/>
      <xsd:choice minOccurs="1" maxOccurs="1">
          <xsd:element name="fullname" type="xsd:string" />
          <xsd:element name="name" type="name" />
      </xsd:choice>
			<xsd:element name="birthdate" type="xsd:date"/>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="email" type="xsd:string"/>
      </xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="username" type="xsd:ID" use="required"/>
		<xsd:attribute name="gender" type="gender" use="optional"/>
	</xsd:complexType>

  <xsd:complexType name="name">
    <xsd:sequence>
      <xsd:element name="firstname" type="xsd:string"/>
      <xsd:element name="lastname" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
	
	<xsd:simpleType name="gender">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="male"/>
			<xsd:enumeration value="female"/>
		</xsd:restriction>
	</xsd:simpleType>

  <xsd:simpleType name="correct">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="no"/>
      <xsd:enumeration value="yes"/>
    </xsd:restriction>
  </xsd:simpleType>
	
	<xsd:complexType name="games">
		<xsd:sequence>
			<xsd:element name="game" type="game" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="game">
		<xsd:sequence>
			<xsd:element name="player" type="player" minOccurs="1" maxOccurs="2"/>
			<xsd:element name="asked" type="asked" minOccurs="0" maxOccurs="10"/>
		</xsd:sequence>
		<xsd:attribute name="session" type="xsd:ID" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="player">
		<xsd:attribute name="ref" type="xsd:IDREF" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="asked">
		<xsd:sequence>
			<xsd:element name="givenanswer" type="givenanswer" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="question" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="givenanswer">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="player" type="xsd:IDREF" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:complexType name="overview" mixed="true">
	    <xsd:choice minOccurs="0" maxOccurs="unbounded">
		   <xsd:element name="a" type="anchor" />
		   <xsd:element name="p" type="overview" />
		</xsd:choice>
	</xsd:complexType>
	
	<xsd:complexType name="anchor">
	   <xsd:simpleContent>
	      <xsd:extension base="xsd:string">
		     <xsd:attribute name="href" type="xsd:string" use="required" />
		  </xsd:extension>
	   </xsd:simpleContent>
	</xsd:complexType>
  
</xsd:schema>

=== l3chtan/SSD/UE3/ssd-ss15-exercise3/output/jeopardy-out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--<!DOCTYPE jeopardy SYSTEM "jeopardy.dtd">--><jeopardy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jeopardy.xsd">
  <overview>
    This <a href="http://dbai.tuwien.ac.at/education/dbs/">Jeopardy</a> quiz is
    really
    <p>
      awesome!
    </p>
  </overview>

  <categories>
    <category name="TV">
      <question id="1" value="100">
        <text>The name of the Simpsons' baby.</text>
        <answer correct="yes">Who is Maggie?</answer>
        <answer>Who is Marge?</answer>
        <answer>Who is Mabel?</answer>
        <answer>Who is Maria?</answer>
      </question>
      <question id="2" value="200">
        <text>Homer's favorite beer.</text>
        <answer>What is Corona?</answer>
        <answer correct="yes">What is Duff?</answer>
        <answer>What is Heineken?</answer>
        <answer>What is Ottakringer?</answer>
      </question>
      <question id="3" value="500">
        <text>A neighbor of the Simpsons.</text>
        <answer correct="yes">Who is Rod Flanders?</answer>
        <answer correct="yes">Who is Tod Flanders?</answer>
        <answer>Who is Brad Fletcher?</answer>
        <answer correct="yes">Who is Ned Flanders?</answer>
        <answer>Who is Patty Bouvier?</answer>
      </question>
      <question id="4" value="750">
        <text>A character in the TV series "The Big Bang Theory".</text>
        <answer correct="yes">Who is Sheldon Lee Cooper?</answer>
        <answer>Who is Malcolm Wilkerson?</answer>
        <answer>Who is Charles Montgomery Burns?</answer>
        <answer correct="yes">Who is Howard Joel Wolowitz?</answer>
        <answer correct="yes">Who is Leonard Leakey Hofstadter?</answer>
      </question>
    </category>
    <category name="TUWIEN">
      <question id="5" value="100">
        <text>These courses are in the modul EWA.</text>
        <answer>What is IT Strategy?</answer>
        <answer correct="yes">What is Web Engineering?</answer>
        <answer>What is Object Oriented Modelling?</answer>
        <answer correct="yes">What is Semistructured Data?</answer>
      </question>
      <question id="6" value="1000">
        <text>TU Vienna has been founded.</text>
        <answer correct="yes">What happened in 1815?</answer>
        <answer>What happened in 1810?</answer>
        <answer>What happened in 1915?</answer>
        <answer>What happened in 2010?</answer>
      </question>
    </category>
    <category name="Web"/>
  </categories>



  <users>
    <user gender="male" username="Bart">
      <password>basi</password>
      <fullname>Bart Simpson</fullname>
      <birthdate>1982-04-01</birthdate>
    </user>

    <user gender="female" username="Lisa">
      <password>lisi</password>
      <name>
        <firstname>Lisa</firstname>
        <lastname>Simpson</lastname>
      </name>
      <birthdate>1984-08-02</birthdate>
    </user>

    <user gender="male" username="Homer">
      <password>hosi</password>
      <name>
        <firstname>Homer</firstname>
        <lastname>Simpson</lastname>
      </name>
      <birthdate>1955-05-10</birthdate>
      <email>homer.simpson@gmail.com</email>
      <email>homer.simpson@hotmail.com</email>
    </user>
  </users>

  <games>
    <game session="abcd">
      <player ref="Bart"/>
      <player ref="Lisa"/>

      <asked question="1">
        <givenanswer player="Bart">Who is Maggie?</givenanswer>
        <givenanswer player="Bart">Who is Maria?</givenanswer>
        <givenanswer player="Lisa">Who is Maggie?</givenanswer>
      </asked>
	  
	  <asked question="4">
	    <givenanswer player="Bart">Who is Sheldon Lee Cooper?</givenanswer>
	    <givenanswer player="Lisa">Who is Sheldon Lee Cooper?</givenanswer>
        <givenanswer alayer="Lisa">Who is Howard Joel Wolowitz?</givenanswer>
        <givenanswer player="Lisa">Who is Leonard Leakey Hofstadter?</givenanswer>
	  </asked>


    </game>
	
    <game session="abc"><player ref="Lisa"/>
		<player ref="Bart"/>
		
		<asked question="5">
			<givenanswer player="Bart">What is Object Oriented Modelling?</givenanswer>
			<givenanswer player="Bart">What is Semistructured Data?</givenanswer>
		<givenanswer player="Lisa">What is Semistructured Data?</givenanswer><givenanswer player="Lisa">What is Web Engineering?</givenanswer></asked>
	</game>
</games>
</jeopardy>
